Repository intuit/ReplayWeb, pull requests merged in 2019-10, with the labels that each got.

#2 Center Readme Image
  README.md
Labels: documentation

#3 add easier setup instructions
  README.md
Labels: documentation

#9 Add crx to release
  .autorc
  .circleci/config.yml
  package.json
  yarn.lock
Labels: internal api

#11 Add README badges
  README.md
Labels: documentation, skip-release

#10 Update README with correct setup links
  README.md
  packages/extension/README.md
  packages/host/README.md
Labels: documentation, skip-release

#12 Add code style badge
  README.md
Labels: documentation, major

#14 test(EnvironmentField): Added tests for EnvironmentField component
  packages/extension/src/components/dashboard/fields/EnvironmentField.jsx
  packages/extension/test/components/dashboard/fields/EnvironmentField.test.js
  packages/utils/src/index.js
  packages/utils/test/index.test.js
Labels: hacktoberfest, internal api, patch

#13 Adding unit test cases to increase code coverage
  packages/extension/test/components/Header.test.js
  yarn.lock
Labels: hacktoberfest, internal api, skip-release

#19 Recommended changes
  packages/utils/test/index.test.js
Labels: hacktoberfest, skip-release

#22 Added unit test cases to increase code coverage
  packages/utils/test/index.test.js
Labels: hacktoberfest, skip-release

#21 test: update node requirement and add small test
  packages/extension/src/components/Modals/DuplicateModal.jsx
  packages/extension/test/components/Modals/DuplicateModal.test.js
  packages/utils/README.md
Labels: hacktoberfest, skip-release

#15 test(utils/xpath): Additional unit test for xpath utils - ignore pattern params
  packages/utils/test/index.test.js
Labels: hacktoberfest, skip-release

#23 Add test for test suite action util addTestToSuite
  packages/extension/test/actions/suites.test.js
  packages/extension/test/actions/utilities.test.js
Labels: hacktoberfest, skip-release

#25 Adding unit test cases to increase code coverage
  packages/extension/test/components/Project/FolderBrowser.test.js
  packages/extension/test/components/Project/ProjectModal.test.js
Labels: hacktoberfest, skip-release

#24 adding additional unit tests to duplicate modal and fixing context bi…
  packages/extension/src/components/Modals/DuplicateModal.jsx
  packages/extension/test/components/Modals/DuplicateModal.test.js
Labels: hacktoberfest, skip-release

#27 Add unit tests for RenameModal
  packages/extension/src/components/Modals/RenameModal.jsx
  packages/extension/test/components/Modals/RenameModal.test.js
Labels: hacktoberfest, skip-release

#26 Update installation documentation for testrunner package
  packages/testrunner/README.md
Labels: documentation, hacktoberfest, skip-release

#28 Adding Test cases for components/Modal/DuplicateModal
  packages/extension/src/components/Modals/DuplicateModal.jsx
  packages/extension/test/components/Modals/DuplicateModal.test.js
  yarn.lock
Labels: hacktoberfest, internal api, skip-release

#29 Added unit tests for packages/extension/src/components/dashboard/DashboardBottom.jsx
  packages/extension/test/components/dashboard/DashboardBottom.test.js
Labels: hacktoberfest, internal api, skip-release

#30 Added tests for dashboard/SuiteEditor.jsx in extension
  packages/extension/src/components/dashboard/SuiteEditor.jsx
  packages/extension/test/components/dashboard/SuiteEditor.test.js
Labels: hacktoberfest, internal api, skip-release

#31 Tests to check that correct input renders based on commands
  packages/extension/test/components/dashboard/fields/OneField.test.js
Labels: hacktoberfest, internal api, skip-release

#32 Adding tests for dashboard/fields/OneField in extension.
  packages/extension/test/components/dashboard/fields/OneField.test.js
Labels: hacktoberfest, internal api, skip-release

#33 Adding more unit tests for utils.test.js
  packages/extension/test/common/utils.test.js
Labels: hacktoberfest, internal api, skip-release

#34 adding unit tests
  packages/extension/test/common/command_runner.test.js
Labels: hacktoberfest, internal api, skip-release

#36 First jsx unit tests
  packages/extension/src/components/dashboard/fields/CommandButtons.jsx
  packages/extension/test/components/dashboard/fields/CommandButtons.test.js
Labels: hacktoberfest, internal api, skip-release

#38 chore: update contributing
  .github/CONTRIBUTING.md
Labels: documentation, hacktoberfest, skip-release

#37 updating the command to support crx 3
  packages/extension/package.json
Labels: bug, hacktoberfest, patch

#39 test: add async tests for suite extentions
  packages/extension/test/actions/suites.test.js
Labels: hacktoberfest, internal api, skip-release

#41 chore: added mode property flag to webpack config
  packages/host/webpack.config.js
  packages/utils/webpack.config.js
Labels: enhancement, hacktoberfest, patch

#43 ShareBlockModal - increase test coverage
  packages/extension/test/components/Modals/ShareBlockModal.test.js
Labels: hacktoberfest, internal api, skip-release
